# Change these first
owner: axiomcorelabs # Your GitHub organization or username, where this repository lives
repo: acl-upptime # The name of this repository

sites:

  - name: Axiom Core - Services
    url: https://www.axiom-core-labs.com
    icon: https://axiom-core-labs.com/favicon.ico
    maxResponseTime: 1500
    
  - name: Resend API - Email & Form Services
    url: https://api.resend.com/contacts
    headers:
      - "Authorization: Bearer $RESEND_API_KEY"
      - "Content-Type: application/json"
    icon: https://resend.com/static/favicons/favicon.ico?v=1
    maxResponseTime: 2000

  - name: Public Client - Factory Park
    url: https://factory-park-immobilier.com/
    icon: https://factory-park-immobilier.com/favicon.ico
    maxResponseTime: 1500

  - name: Public Client - Marie Grosset
    url: https://osteopathe-mariegrosset.com/
    icon: https://osteopathe-mariegrosset.com/favicon.ico
    maxResponseTime: 1500

   - name: Public Client - Arthur Lebas Etiopathe
    url: https://www.arthur-lebas-etiopathe.com/
    icon: https://www.arthur-lebas-etiopathe.com/favicon.ico
    maxResponseTime: 1500
    
  - name: Public Client - Claire Labbe Osteopathe
    url: https://clairelabbeosteopathe.com/
    icon: https://clairelabbeosteopathe.com/favicon.ico
    maxResponseTime: 1500
    
  - name: Private Client - 15A1D79
    url: $PRIVATE_CLIENT_15A1D79_URL
    icon: https://axiom-core-labs.com/favicon.ico
    maxResponseTime: 1500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.axiom-core-labs.com
  # baseUrl: /acl-upptime
  logoUrl: https://status.axiom-core-labs.com/acl-icon.svg
  themeUrl: https://status.axiom-core-labs.com/acl-website-theme.css
  favicon: https://status.axiom-core-labs.com/favicon.png
  faviconSvg: https://status.axiom-core-labs.com/favicon.svg
  name: Axiom Core - Status
  introTitle: "**Axiom Core** status page."
  introMessage: This status page data updates **every 30 minutes**.
  navbar:
    - title: Status
      href: /
    # - title: Status Links
    #   href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
