# Change these first
owner: axiomcorelabs # Your GitHub organization or username, where this repository lives
repo: acl-upptime # The name of this repository

sites:

  - name: Axiom Core Labs - Services
    url: https://www.axiom-core-labs.com
    icon: https://axiom-core-labs.com/favicon.ico
    maxResponseTime: 5000
    
  - name: Cloudflare - Hosting Services
    url: https://www.cloudflarestatus.com/
    maxResponseTime: 5000
    
  - name: Resend API - Email & Form Services
    url: https://api.resend.com/contacts
    headers:
      - "Authorization: Bearer $RESEND_API_KEY"
      - "Content-Type: application/json"
    icon: https://resend.com/static/favicons/favicon.ico?v=1
    maxResponseTime: 15000
    
  - name: Claire Labbe Osteopathe
    url: https://clairelabbeosteopathe.com/
    icon: https://clairelabbeosteopathe.com/favicon.ico
    maxResponseTime: 5000
    
  - name: Arthur Lebas Etiopathe
    url: https://www.arthur-lebas-etiopathe.com/
    icon: https://www.arthur-lebas-etiopathe.com/favicon.ico
    maxResponseTime: 5000
    
  - name: Private Client - 15A1D79
    url: $PRIVATE_CLIENT_15A1D79_URL
    icon: https://axiom-core-labs.com/favicon.ico
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.axiom-core-labs.com
  # baseUrl: /acl-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Axiom Core Labs - Status
  introTitle: "**Axiom Core Labs** uptime monitor and status page."
  introMessage: This status page data updates **every 30 minutes**.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
